<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit99cec8e9d6ccc6187d3d24b55c98a562
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'StrongAndFit\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'StrongAndFit\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit99cec8e9d6ccc6187d3d24b55c98a562::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit99cec8e9d6ccc6187d3d24b55c98a562::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit99cec8e9d6ccc6187d3d24b55c98a562::$classMap;

        }, null, ClassLoader::class);
    }
}
